DROP TABLE COURSE_DATE;
DROP TABLE COURSE_ORDER;
DROP TABLE COUPON;
DROP TABLE COURSE_FAVOR;
DROP TABLE COURSE_SET;
DROP TABLE COURSE;
-------------------------------------------------------
--一對一課程
CREATE TABLE COURSE(
	COURSE_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	COACH_ID VARCHAR2(10) NOT NULL,
	CNAME VARCHAR2(300) NOT NULL,
	INTRO VARCHAR2(4000),
	EXP_ID VARCHAR2(5) NOT NULL,
	LOC VARCHAR2(300) NOT NULL,
	PIC1 BLOB,
	PIC2 BLOB,
	PIC3 BLOB,
	INITSTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATE NUMBER(1,0) NOT NULL,
    FOREIGN KEY (COACH_ID) REFERENCES COACH (COACH_ID),
    FOREIGN KEY (EXP_ID) REFERENCES EXPTYPE (EXP_ID)
);
--一對一課程方案	
CREATE TABLE COURSE_SET(
	SET_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	COURSE_ID VARCHAR2(10) NOT NULL,
	LESSON NUMBER(2,0) NOT NULL,
	PRICE NUMBER(6,0) NOT NULL,
	FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);
--一對一課程最愛
CREATE TABLE COURSE_FAVOR(
    MEMBER_ID VARCHAR2(10) NOT NULL,
	COURSE_ID VARCHAR2(10) NOT NULL,	
	CONSTRAINT PK_COURSE_FAVOR PRIMARY KEY (MEMBER_ID, COURSE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);
--一折價券
CREATE TABLE COUPON(
	COUPON_ID VARCHAR2(8) PRIMARY KEY NOT NULL,
	COUPON_DISC NUMBER(6,0) NOT NULL,
	STATE NUMBER(1,0) NOT NULL
);
--一對一課程訂單
CREATE TABLE COURSE_ORDER(
	ORDER_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	MEMBER_ID VARCHAR2(10) NOT NULL,
	SET_ID VARCHAR2(10) NOT NULL,
	LESSON NUMBER(2,0) NOT NULL,
	ORDER_PRICE NUMBER(6,0) NOT NULL,
	COUPON_ID VARCHAR2(8),
	DISC NUMBER(6,0),
	TOTAL_PRICE NUMBER(6,0) NOT NULL,
	BOOK_LESSON NUMBER(2,0) NOT NULL,
	INITSTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COM_STAR NUMBER(1,0),
	COM_CONTENT VARCHAR2(300),
	COM_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATE NUMBER(1,0) NOT NULL,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	FOREIGN KEY (SET_ID) REFERENCES COURSE_SET (SET_ID),
	FOREIGN KEY (COUPON_ID) REFERENCES COUPON (COUPON_ID)
);
--一對一課程約課時間
CREATE TABLE COURSE_DATE(
	CDATE_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	ORDER_ID VARCHAR2(10) NOT NULL,
	CDATE DATE NOT NULL,
	CTIME VARCHAR2(24) NOT NULL,
	INITSTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATE NUMBER(1,0) NOT NULL,
	FOREIGN KEY (ORDER_ID) REFERENCES COURSE_ORDER (ORDER_ID)
);