DROP SEQUENCE COURSE_SET_SEQ;

CREATE SEQUENCE COURSE_SET_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

----------------------------------

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 1, 2000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 12, 21600);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 24, 40800);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 36, 57600);

----------------------------------

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20002', 10, 20000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20002', 20, 32000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20002', 30, 42000);

----------------------------------

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20003', 1, 3000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20003', 10, 30000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20003', 20, 60000);

----------------------------------

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20004', 1, 8000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20004', 10, 7500);

----------------------------------

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 1, 2000);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 12, 20400);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 24, 33600);

INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 36, 46800);

COMMIT;