--移除TABLE及SEQ
DROP TABLE COURSE_DATE;
DROP TABLE COURSE_ORDER;
DROP TABLE COUPON;
DROP TABLE COURSE_FAVOR;
DROP TABLE COURSE_SET;
DROP TABLE COURSE;

DROP SEQUENCE COURSE_DATE_SEQ;
DROP SEQUENCE COURSE_ORDER_SEQ;
DROP SEQUENCE COURSE_SET_SEQ;
DROP SEQUENCE COURSE_SEQ;

-------------------------------------------------------------

--創建表格
--一對一課程
CREATE TABLE COURSE(
	COURSE_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	COACH_ID VARCHAR2(10) NOT NULL,
	CNAME VARCHAR2(300) NOT NULL,
	INTRO VARCHAR2(4000),
	EXP_ID VARCHAR2(5) NOT NULL,
	LOC VARCHAR2(300) NOT NULL,
	PIC1 BLOB,
	PIC2 BLOB,
	PIC3 BLOB,
	INITSTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATE NUMBER(1,0) NOT NULL,
    FOREIGN KEY (COACH_ID) REFERENCES COACH (COACH_ID),
    FOREIGN KEY (EXP_ID) REFERENCES EXPTYPE (EXP_ID)
);
--一對一課程方案	
CREATE TABLE COURSE_SET(
	SET_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	COURSE_ID VARCHAR2(10) NOT NULL,
	LESSON NUMBER(2,0) NOT NULL,
	PRICE NUMBER(6,0) NOT NULL,
	FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);
--一對一課程最愛
CREATE TABLE COURSE_FAVOR(
    MEMBER_ID VARCHAR2(10) NOT NULL,
	COURSE_ID VARCHAR2(10) NOT NULL,	
	CONSTRAINT PK_COURSE_FAVOR PRIMARY KEY (MEMBER_ID, COURSE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);
--一折價券
CREATE TABLE COUPON(
	COUPON_ID VARCHAR2(8) PRIMARY KEY NOT NULL,
	COUPON_DISC NUMBER(6,0) NOT NULL,
	STATE NUMBER(1,0) NOT NULL
);
--一對一課程訂單
CREATE TABLE COURSE_ORDER(
	ORDER_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	MEMBER_ID VARCHAR2(10) NOT NULL,
	SET_ID VARCHAR2(10) NOT NULL,
	LESSON NUMBER(2,0) NOT NULL,
	ORDER_PRICE NUMBER(6,0) NOT NULL,
	COUPON_ID VARCHAR2(8),
	DISC NUMBER(6,0),
	TOTAL_PRICE NUMBER(6,0) NOT NULL,
	BOOK_LESSON NUMBER(2,0) NOT NULL,
	INITSTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COM_STAR NUMBER(1,0),
	COM_CONTENT VARCHAR2(300),
	COM_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATE NUMBER(1,0) NOT NULL,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	FOREIGN KEY (SET_ID) REFERENCES COURSE_SET (SET_ID),
	FOREIGN KEY (COUPON_ID) REFERENCES COUPON (COUPON_ID)
);
--一對一課程約課時間
CREATE TABLE COURSE_DATE(
	CDATE_ID VARCHAR2(10) PRIMARY KEY NOT NULL,
	ORDER_ID VARCHAR2(10) NOT NULL,
	CDATE DATE NOT NULL,
	CTIME VARCHAR2(24) NOT NULL,
	INITSTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATE NUMBER(1,0) NOT NULL,
	FOREIGN KEY (ORDER_ID) REFERENCES COURSE_ORDER (ORDER_ID)
);

-------------------------------------------------------------

--創建SEQ
CREATE SEQUENCE COURSE_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSE_SET_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSE_ORDER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE COURSE_DATE_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-------------------------------------------------------------

--[INSERT] COURSE
INSERT INTO COURSE (COURSE_ID, COACH_ID, CNAME, INTRO, EXP_ID, LOC, STATE) 
VALUES ('C20' || LPAD(COURSE_SEQ.NEXTVAL, 3, '0'), 
'C01', 
'🥇私人教練最佳好評💯！增肌健身健體減脂', 
'身高185 健美運動員

個人健身15年經驗 🥇
教學12年經驗 🥇

【私人健身課程】
專業教練幫你在✔最短時間✔有效✔練出好身材，不分男女年齡，歡迎上課練出一身好體態！

✅增肌：一對一訓練指導，針對肌肉控制、神經連結、肌肉控制學習
✅減脂、減重：客製化個人飲食菜單，搭配週期訓練
✅體態雕塑：雕塑身形，培養運動習慣，基礎訓練內容安排

教練規劃完整的訓練週期，搭配運動飲食菜單讓體態呈現效果更好🔥

歡迎私訊了解



■教練1對1正確指導，不用再盲目自己苦練。
■壯碩教練以身作則，課程效果看得到。
■課後追蹤，務求完整生活改變。
■教練不會更換，全程帶你邁向目標。


重視基礎 ！安全性！ 惟有最紮實的基礎才有之後的效果！！🏆', 
'S03', 
'桃園市中壢區', 
'1');

INSERT INTO COURSE (COURSE_ID, COACH_ID, CNAME, INTRO, EXP_ID, LOC, STATE) 
VALUES ('C20' || LPAD(COURSE_SEQ.NEXTVAL, 3, '0'), 
'C02', 
'平均3個月瘦5%體脂肪｜體態雕塑', 
'透過運動改善身材、增加自信、找到更好的自己

專業經驗：
學生上課3個月可以有明顯線條和進步
學生平均3個月瘦5%體脂肪，體重下降7公斤
改善文明病，例如腰酸背痛、肩頸痠痛
讓銀髮族能跟年輕人一樣活動自如，不需要人照顧

證照：
美國有氧體適能協會-個人體適能顧問PFT
美國有氧體適能協會-重量訓練指導員WT
中華民國體適能C級教練
中華民國健力協會C級教練
EMT-1初級救護員

學經歷：
台北市立大學運動健康科學系
士林運動中心教練
萬華運動中心培訓教練
力康健康管理中心助理教練
Bodyfighter fitness教練
Crossfit loga團課教練
聚廠工作室團課教練

專長：
一對一個人指導
體態雕塑
功能性訓練
姿勢評估
增肌/減脂/減重指導
傷後復健運動訓練
運動按摩', 
'S03', 
'台北市士林區', 
'1');

INSERT INTO COURSE (COURSE_ID, COACH_ID, CNAME, INTRO, EXP_ID, LOC, STATE) 
VALUES ('C20' || LPAD(COURSE_SEQ.NEXTVAL, 3, '0'), 
'C03', 
'噶瑪蘭戰士-潘弘旻：泰拳教練/現役國手', 
'🥊鍾情於泰拳的噶瑪蘭戰士💦
　　潘弘旻Opay Omos，花蓮豐濱新社部落的噶瑪蘭族人。

🥊主動出擊，無所畏懼。💦
　　堅持不懈咬緊牙關苦練多年，從國內業餘賽、國外職業賽再到站上世界級泰拳賽事擂台，噶瑪蘭戰士潘弘旻無所畏懼：
🏅2015 中國職業賽 英雄傳說重慶站 68kg KO日本職業選手記村一成
🏅2015 全國泰拳錦標賽 71kg冠軍／最佳美技獎
🏅2015 IFMA世界泰拳錦標賽 71kg第五名
🏅2015 兩岸四地泰拳錦標賽 71kg特別賽事優勝
🏅2015 越南Trận 5 Muay泰拳職業賽 81kg優勝
🏅2015 世界自由搏擊聯合會拳王爭霸賽  68kg優勝
🏅2018 全國泰拳錦標賽 75kg冠軍／最佳美技獎 
🏅2018 猛龍過江職業技擊爭霸賽 自由搏擊 75kg優勝

🥊優勝時刻💦
　　2015年7月潘弘旻至中國重慶參加英雄傳說職業賽，一分鐘擊倒日本職業選手記村一成，獲得優勝（比賽影片2分10秒開始：https://goo.gl/hFshJv）。
 　　回臺後，緊接著參加全國業餘泰拳錦標賽暨國家選手選拔，勇奪71公斤量級冠軍，並代表臺灣出征世界泰拳錦標賽。
　　2015 IFMA世界泰拳錦標賽有多達十八國菁英選手參賽角逐，潘弘旻出戰保加利亞籍強勁對手，初試啼聲即締造世界泰拳第五名的亮眼戰績（報導及比賽影片：https://goo.gl/Fhvk4f）。
　　同年10月份受兩岸四地暨國際泰拳邀請賽盛情邀約，於71公斤量級特別賽事對戰泰國拳王佳龍，榮獲優勝（比賽影片：https://goo.gl/EQos9H）。

🥊選擇我💦
格鬥部落創辦人/教練、中華民國泰國拳協會-教練、中華民國散打搏擊協會-裁判、泰拳中華隊-國手、中國/東南亞搏擊職業賽事-選手，想了解更多歡迎私訊', 
'S04', 
'花蓮縣花蓮市', 
'1');

INSERT INTO COURSE (COURSE_ID, COACH_ID, CNAME, INTRO, EXP_ID, LOC, STATE) 
VALUES ('C20' || LPAD(COURSE_SEQ.NEXTVAL, 3, '0'), 
'C04', 
'台中縣市游泳保證班/私人游泳教練', 
'● 教練：旺旺教練與專業的教學團隊
● 職業：私人專業教練
● 相關證照：救生員證、C級教練證、PADI二階進階潛水執照
【 相關報導 】
2014年馬尼亞納觀光大使選拔前三名
2015年超視余美人談話性節目「型男老師」
2016年中天新聞「專題報導」高顏質私人游泳教練
【 教學經驗 】
豐富；水域活動接觸10年以上
曾在帛琉擔任當地擔任駐地導遊2年 ( 浮潛教練 )', 
'S08', 
'台中市大甲區', 
'1');

INSERT INTO COURSE (COURSE_ID, COACH_ID, CNAME, INTRO, EXP_ID, LOC, STATE) 
VALUES ('C20' || LPAD(COURSE_SEQ.NEXTVAL, 3, '0'), 
'C01', 
'從零開始的增肌訓練課', 
'【運動課程】從零開始的增肌訓練課
課程介紹》http://bit.ly/3c2brS5
　
這門課會將增肌訓練觀念由淺入深，透過俐落的口白與超詳細的動作解說，幫助你一次掌握增肌訓練的所有細節！
讓你不再因為擔心不會使用健身房的各種器具，而總是默默走去跑步機！', 
'S01', 
'桃園市中壢區', 
'1');

COMMIT;

-------------------------------------------------------------

--[INSERT] COURSE_SET
--課程20001
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 1, 2000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 12, 21600);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 24, 40800);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20001', 36, 57600);

--課程20002
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20002', 10, 20000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20002', 20, 32000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20002', 30, 42000);

--課程20003
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20003', 1, 3000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20003', 10, 30000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20003', 20, 60000);

--課程20004
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20004', 1, 8000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20004', 10, 7500);

--課程20005
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 1, 2000);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 12, 20400);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 24, 33600);
INSERT INTO COURSE_SET (SET_ID, COURSE_ID, LESSON, PRICE) 
VALUES ('CS20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'C20005', 36, 46800);

COMMIT;

-------------------------------------------------------------

--[INSERT] COURSE_FAVOR
INSERT INTO COURSE_FAVOR (MEMBER_ID, COURSE_ID) VALUES ('M001', 'C20001');
INSERT INTO COURSE_FAVOR (MEMBER_ID, COURSE_ID) VALUES ('M001', 'C20002');
INSERT INTO COURSE_FAVOR (MEMBER_ID, COURSE_ID) VALUES ('M001', 'C20005');
INSERT INTO COURSE_FAVOR (MEMBER_ID, COURSE_ID) VALUES ('M002', 'C20003');
INSERT INTO COURSE_FAVOR (MEMBER_ID, COURSE_ID) VALUES ('M003', 'C20001');
INSERT INTO COURSE_FAVOR (MEMBER_ID, COURSE_ID) VALUES ('M004', 'C20002');
COMMIT;

-------------------------------------------------------------

--[INSERT] COUPON
INSERT INTO COUPON (COUPON_ID, COUPON_DISC, STATE) VALUES ('83190672', 100, 1);
INSERT INTO COUPON (COUPON_ID, COUPON_DISC, STATE) VALUES ('30197002', 100, 1);
INSERT INTO COUPON (COUPON_ID, COUPON_DISC, STATE) VALUES ('19114421', 100, 0);
INSERT INTO COUPON (COUPON_ID, COUPON_DISC, STATE) VALUES ('91276751', 100, 0);
INSERT INTO COUPON (COUPON_ID, COUPON_DISC, STATE) VALUES ('98480596', 100, 0);
INSERT INTO COUPON (COUPON_ID, COUPON_DISC, STATE) VALUES ('50677273', 100, 0);
COMMIT;

-------------------------------------------------------------

--[INSERT] COURSE_ORDER
--4已付款已完課(訂單完成)
INSERT INTO COURSE_ORDER (ORDER_ID, MEMBER_ID, SET_ID, LESSON, ORDER_PRICE, COUPON_ID, DISC, TOTAL_PRICE, BOOK_LESSON, COM_STAR, COM_CONTENT, STATE) 
VALUES ('CO20' || LPAD(COURSE_ORDER_SEQ.NEXTVAL, 3, '0'), 'M001', 'CS20001', 1, 2000, '83190672', 100, 1900, 1, 4, '教練認真不會推銷', 4);
--3已付款未完課
INSERT INTO COURSE_ORDER (ORDER_ID, MEMBER_ID, SET_ID, LESSON, ORDER_PRICE, COUPON_ID, DISC, TOTAL_PRICE, BOOK_LESSON, STATE) 
VALUES ('CO20' || LPAD(COURSE_ORDER_SEQ.NEXTVAL, 3, '0'), 'M002', 'CS20004', 36, 57600, '30197002', 100, 57500, 2, 3);
--2教練已確認未付款
INSERT INTO COURSE_ORDER (ORDER_ID, MEMBER_ID, SET_ID, LESSON, ORDER_PRICE, TOTAL_PRICE, BOOK_LESSON, STATE) 
VALUES ('CO20' || LPAD(COURSE_ORDER_SEQ.NEXTVAL, 3, '0'), 'M003', 'CS20011', 1, 8000, 8000, 0, 2);
--1訂單取消
INSERT INTO COURSE_ORDER (ORDER_ID, MEMBER_ID, SET_ID, LESSON, ORDER_PRICE, TOTAL_PRICE, BOOK_LESSON, STATE) 
VALUES ('CO20' || LPAD(COURSE_ORDER_SEQ.NEXTVAL, 3, '0'), 'M003', 'CS20011', 1, 8000, 8000, 0, 1);
--0教練未確認
INSERT INTO COURSE_ORDER (ORDER_ID, MEMBER_ID, SET_ID, LESSON, ORDER_PRICE, TOTAL_PRICE, BOOK_LESSON, STATE) 
VALUES ('CO20' || LPAD(COURSE_ORDER_SEQ.NEXTVAL, 3, '0'), 'M004', 'CS20009', 10, 30000, 30000, 0, 0);
--3已付款未完課
INSERT INTO COURSE_ORDER (ORDER_ID, MEMBER_ID, SET_ID, LESSON, ORDER_PRICE, TOTAL_PRICE, BOOK_LESSON, STATE) 
VALUES ('CO20' || LPAD(COURSE_ORDER_SEQ.NEXTVAL, 3, '0'), 'M006', 'CS20013', 1, 2000, 2000, 0, 3);

COMMIT;

-------------------------------------------------------------

--[INSERT] COURSE_DATE
--2教練已確認已上課
INSERT INTO COURSE_DATE (CDATE_ID, ORDER_ID, CDATE, CTIME, STATE)
VALUES ('CD20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'CO20001', TO_DATE('2020-07-29', 'YYYY-MM-DD'), '000000000000000000110000', 2);
--1教練已確認未上課
INSERT INTO COURSE_DATE (CDATE_ID, ORDER_ID, CDATE, CTIME, STATE)
VALUES ('CD20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'CO20002', TO_DATE('2020-07-29', 'YYYY-MM-DD'), '000000000000000000110000', 1);
--0教練未確認
INSERT INTO COURSE_DATE (CDATE_ID, ORDER_ID, CDATE, CTIME, STATE)
VALUES ('CD20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'CO20002', TO_DATE('2020-07-30', 'YYYY-MM-DD'), '000000000000000000110000', 0);
--3約課取消
INSERT INTO COURSE_DATE (CDATE_ID, ORDER_ID, CDATE, CTIME, STATE)
VALUES ('CD20' || LPAD(COURSE_SET_SEQ.NEXTVAL, 3, '0'), 'CO20002', TO_DATE('2020-07-31', 'YYYY-MM-DD'), '000000000000000000110000', 3);

COMMIT;